### ISSUE TITLE
Still experimental?

### ISSUE THREAD

**Issue by daurnimator** [ibarwick/firebird_fdw#4]
Is this module still considered experiemental?
Is it still being maintained?

**Comment by mbecroft** [comment]
daurnimator <notifications@github.com> writes:

> Is this module still considered experiemental?
> Is it still being maintained?

Greetings,

We use firebird_fdw in production for clients at True Group, and have
outstanding pull requests from about 2 years ago. I believe ibarwick,
the maintainer, has made some other improvements in the last year or
so...so I suppose it is maintained, but it's a bit of a niche product so
the level of activity is not high. For one thing, none of our pull
requests have been actioned...at some point we'll rebase ours with
ibarwick's latest changes and try again.

Part of the trouble is that it is maintained by 2nd Quadrant, who are
not very interested in doing anything (even accepting simple pull
requests for obvious bug fixes or feature improvements) unless they are
being paid for it.

We are aware of at least one 'crashes postgres' bug, the fix for which
is on our todo list, but we have a workaround in place, so it may be a
few months...

It would be good to network with others using this module. So let's all
keep in touch via this ticket for now, or directly.

I don't have it on me, but when I do, I will update this with a link to
the True Group repos. If we still can't get anything out of 2nd
Quadrant, then it may be that our version becomes the de-facto free
version and 2nd Quadrant may pull from us when they feel like it for
their paying clients.

Feel free to reach out with any questions or if you need help. We are
pretty familiar with the module and run it in multiple production
environments, and happy to share our knowledge.

Cheers,

-- 
Mario Becroft <mb@becroft.co.nz>       t: @MarioBecroft
p: +64-9-974-9244  m: +64-21-038-5178  w: http://www.becroft.co.nz/

**Comment by daurnimator** [comment]
> I believe ibarwick, the maintainer, has made some other improvements in the last year or so...

The last commit was in 2016

> For one thing, none of our pull requests have been actioned

I'm only seeing a single PR open (and none closed), and it's not by you?

**Comment by mbecroft** [comment]
daurnimator <notifications@github.com> writes:

>> I believe ibarwick, the maintainer, has made some other improvements in the last year or so...
>
> The last commit was in 2016

I'm only going on something my colleague mentioned to me a few months
back; possibly I am mistaken, or he was referring to another repo
maintained by someone else.

>> For one thing, none of our pull requests have been actioned
>
> I'm only seeing a single PR open (and none closed), and it's not by you?

It would not have my name on it, as it is maintained by a member of my
team.

Will check what's up with this on Monday.

Is there anything preventing you using the extension right now?
Probably compatibility with current pg version, for a start. I can help
you there. Let me see on Monday.

Cheers,

-- 
Mario Becroft <mb@becroft.co.nz>       t: @MarioBecroft
p: +64-9-974-9244  m: +64-21-038-5178  w: http://www.becroft.co.nz/

**Comment by daurnimator** [comment]
> Is there anything preventing you using the extension right now?

It influences the architecture for an product that isn't written yet. The product needs to interact with a firebird database; I'm trying to figure out if firebird_fdw is mature enough to talk to it directly from postgres, or if we need to do it from some other process.
So far it sounds like firebird_fdw is *not* mature enough; and seems mostly unmaintained.

**Comment by mbecroft** [comment]
daurnimator <notifications@github.com> writes:

> So far it sounds like firebird_fdw is *not* mature enough; and seems
> mostly unmaintained.

I would say it could be mature enough; we have had it in production for
a good 3 years. There is only one known crash bug we have found but not
had the time or motivation to fix. Other than that, we have had zero
issues after running it in production for several years.

2nd Quadrant will maintain it for you, for a fee.

My company also maintains it. Please feel free to contact me directly on
mb@true.group if I can help you further (no charge) to assess it for
your use-case.

Really, not much maintenance is needed except keeping it up-to-date with
current pg versions.

I don't know about your use case, but we find it very convenient having
a direct foreign table interface to Firebird databases, as queries can
seamlessly access data from the local database, other sources, and
Firebird databases. You can create a view that pulls data from all of
the above, and the poor middleware or front-end developer doesn't have
to know or care how and where all the data is being obtained.

Good luck with your project and selection of suitable technologies.

Cheers,

-- 
Mario Becroft <mb@becroft.co.nz>       t: @MarioBecroft
p: +64-9-974-9244  m: +64-21-038-5178  w: http://www.becroft.co.nz/

**Comment by ibarwick** [comment]
Hi, yes unfortunately this is not really being maintained at the moment; it's a personal project which is dependent on the very limited amount of free time I've had available over the last couple of years, and as  @mbecroft mentioned, it is a very niche application. Funnily enough I was thinking about this the other day, as I may have a bit more time soon, though can't promise anything at this point.

**Comment by ibarwick** [comment]
It lives, it lives... FYI I've done some major cleanup on both this and the `libfq` API, hopefully fixing some of the more visible issues, which should result in a tagged release "soon" (though bear in mind this is still very much a personal free-time project and circumstances can change any time).
